UPD: Updated SpringBoot Lab0 - Added Repositories for Entities - Program keeps failing because it can't find the Author Entity required by the Publication.author field.
Error: j.LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: Association 'com.springbootlab0.approach_1.domain.Publication.author' targets an unknown entity named 'com.springbootlab0.approach_1.domain.Author'